CURRICULUM = {
    "Mathematics": {
        "6": {
            "Chapter 1: Knowing Our Numbers": ["Introduction to Large Numbers","Comparing Numbers","Estimation","Roman Numerals","Place Value"],
            "Chapter 2: Whole Numbers": ["Natural Numbers and Whole Numbers","Number Line","Properties of Whole Numbers","Patterns in Whole Numbers"],
            "Chapter 3: Playing with Numbers": ["Factors and Multiples","Prime and Composite Numbers","HCF and LCM","Divisibility Rules","Prime Factorisation"],
            "Chapter 4: Basic Geometrical Ideas": ["Points, Lines, Line Segments","Angles","Triangles","Quadrilaterals","Circles"],
            "Chapter 5: Understanding Elementary Shapes": ["Measuring Line Segments","Types of Angles","Types of Triangles","Polygons","Three Dimensional Shapes"],
            "Chapter 6: Integers": ["Introduction to Integers","Integers on Number Line","Addition of Integers","Subtraction of Integers"],
            "Chapter 7: Fractions": ["Introduction to Fractions","Types of Fractions","Equivalent Fractions","Addition and Subtraction of Fractions","Comparison of Fractions"],
            "Chapter 8: Decimals": ["Introduction to Decimals","Comparing Decimals","Addition and Subtraction of Decimals","Uses of Decimals in Daily Life"],
            "Chapter 9: Data Handling": ["Recording Data","Organisation of Data","Pictograph","Bar Graph"],
            "Chapter 10: Mensuration": ["Perimeter of Regular Shapes","Perimeter of Rectangles","Area of a Rectangle and Square","Irregular Shapes"],
            "Chapter 11: Algebra": ["Introduction to Algebra","Matchstick Patterns","Idea of Variables","Expressions with Variables","Simple Equations"],
            "Chapter 12: Ratio and Proportion": ["Ratio","Proportion","Unitary Method"],
            "Chapter 13: Symmetry": ["Lines of Symmetry","Symmetrical Figures","Reflection and Symmetry"],
            "Chapter 14: Practical Geometry": ["Construction of Circle","Construction of Line Segment","Construction of Angles","Construction of Perpendicular Bisector"],
        },
        "7": {
            "Chapter 1: Integers": ["Properties of Integers","Multiplication of Integers","Division of Integers","Word Problems on Integers"],
            "Chapter 2: Fractions and Decimals": ["Multiplication of Fractions","Division of Fractions","Multiplication of Decimals","Division of Decimals"],
            "Chapter 3: Data Handling": ["Arithmetic Mean","Mode and Median","Bar Graph (Double)","Probability - Introduction"],
            "Chapter 4: Simple Equations": ["Setting Up Equations","Solving Simple Equations","Applications of Simple Equations"],
            "Chapter 5: Lines and Angles": ["Related Angles","Pairs of Lines","Checking for Parallel Lines","Transversal"],
            "Chapter 6: The Triangle and Its Properties": ["Medians and Altitudes","Exterior Angle Property","Angle Sum Property","Right-Angled Triangles - Pythagoras Theorem","Sum of Lengths of Two Sides"],
            "Chapter 7: Congruence of Triangles": ["Introduction to Congruence","Criteria for Congruence","SAS, ASA, SSS, RHS Congruence"],
            "Chapter 8: Comparing Quantities": ["Equivalent Ratios","Percentage","Profit and Loss","Simple Interest"],
            "Chapter 9: Rational Numbers": ["Introduction to Rational Numbers","Positive and Negative Rational Numbers","Rational Numbers on Number Line","Operations on Rational Numbers"],
            "Chapter 10: Practical Geometry": ["Construction of Parallel Lines","Construction of Triangles"],
            "Chapter 11: Perimeter and Area": ["Squares and Rectangles","Area of Triangle","Area of Parallelogram","Circles - Circumference and Area"],
            "Chapter 12: Algebraic Expressions": ["Introduction to Algebraic Expressions","Terms, Factors, Coefficients","Addition and Subtraction of Algebraic Expressions","Finding the Value of Expressions"],
            "Chapter 13: Exponents and Powers": ["Introduction to Exponents","Laws of Exponents","Decimal Number System","Expressing Large Numbers"],
            "Chapter 14: Symmetry": ["Lines of Symmetry","Rotational Symmetry","Line and Rotational Symmetry"],
            "Chapter 15: Visualising Solid Shapes": ["Plane Figures and Solid Shapes","Faces, Edges, Vertices","Nets of Solid Shapes","Drawing Solids on Flat Surfaces"],
        },
        "8": {
            "Chapter 1: Rational Numbers": ["Properties of Rational Numbers","Representation on Number Line","Rational Numbers Between Two Rational Numbers"],
            "Chapter 2: Linear Equations in One Variable": ["Linear Equations","Solving Linear Equations","Reducing Equations to Simpler Form","Word Problems"],
            "Chapter 3: Understanding Quadrilaterals": ["Polygons","Sum of Measures of Exterior Angles","Kinds of Quadrilaterals","Properties of Parallelogram"],
            "Chapter 4: Data Handling": ["Organising Data","Pie Chart","Chance and Probability","Histogram"],
            "Chapter 5: Squares and Square Roots": ["Properties of Square Numbers","Finding Square Roots","Pythagorean Triplets","Square Root by Long Division"],
            "Chapter 6: Cubes and Cube Roots": ["Cubes","Cube Roots","Properties of Cube Numbers"],
            "Chapter 7: Comparing Quantities": ["Recalling Ratios and Percentages","Compound Interest","Deducing Formula for Compound Interest","Discount and Sales Tax"],
            "Chapter 8: Algebraic Expressions and Identities": ["Algebraic Expressions","Multiplication of Algebraic Expressions","Standard Identities","Applying Identities"],
            "Chapter 9: Mensuration": ["Area of Trapezium","Area of General Quadrilateral","Area of Polygons","Surface Area of Cylinder and Cube","Volume of Cylinder and Cube"],
            "Chapter 10: Exponents and Powers": ["Powers with Negative Exponents","Laws of Exponents","Scientific Notation"],
            "Chapter 11: Direct and Inverse Proportions": ["Direct Proportion","Inverse Proportion","Applications"],
            "Chapter 12: Factorisation": ["Factors of Natural Numbers","Factors of Algebraic Expressions","Division of Algebraic Expressions","Factorisation by Regrouping Terms"],
            "Chapter 13: Introduction to Graphs": ["Bar Graph and Pie Chart","Line Graph","Linear Graph","Applications of Graphs"],
        },
    },
    "Computer Science": {
        "6": {
            "Chapter 1: Computer Fundamentals": ["What is a Computer?","Characteristics of a Computer","Block Diagram of a Computer","Types of Computers","Uses of Computers"],
            "Chapter 2: Hardware and Software": ["Introduction to Hardware","Input Devices","Output Devices","Storage Devices","Introduction to Software","Types of Software"],
            "Chapter 3: Windows Operating System": ["Introduction to Operating System","Features of Windows","Desktop, Taskbar and Icons","Working with Windows","File and Folder Management"],
            "Chapter 4: MS Word - Basic": ["Introduction to Word Processing","Creating and Saving Documents","Formatting Text","Editing Text - Cut, Copy, Paste","Page Setup and Printing"],
            "Chapter 5: MS Paint": ["Introduction to MS Paint","Drawing Tools","Colouring Tools","Text Tool","Saving and Opening Files"],
            "Chapter 6: Internet Basics": ["What is Internet?","History of Internet","Connecting to Internet","Web Browser and Websites","Email Basics"],
        },
        "7": {
            "Chapter 1: Advanced Features of Windows": ["Control Panel Settings","Accessibility Options","System Tools","Windows Shortcuts"],
            "Chapter 2: MS Word - Advanced": ["Tables in MS Word","Inserting Images and Shapes","Mail Merge","Headers, Footers and Page Numbers","Styles and Templates"],
            "Chapter 3: MS Excel - Basics": ["Introduction to Spreadsheet","Rows, Columns and Cells","Entering Data","Basic Formulas","Charts and Graphs"],
            "Chapter 4: MS PowerPoint": ["Introduction to Presentation Software","Creating Slides","Adding Text and Images","Slide Layouts and Themes","Animations and Transitions","Presenting a Slideshow"],
            "Chapter 5: Introduction to Programming": ["What is Programming?","Algorithm and Flowchart","Introduction to Scratch","Sprites and Backgrounds","Events and Controls in Scratch"],
            "Chapter 6: Internet and Cyber Safety": ["World Wide Web","Search Engines","Online Safety and Privacy","Cyber Bullying","Digital Footprint"],
        },
        "8": {
            "Chapter 1: Advanced MS Excel": ["Functions in Excel (SUM, AVG, MAX, MIN)","Conditional Formatting","Sorting and Filtering","VLOOKUP Basics","Pivot Tables Introduction"],
        }}
